apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresDeployment.secrets.metadata.name }}
type: {{ .Values.postgresDeployment.secrets.type }}
data:
  {{- range $key, $value := .Values.postgresDeployment.secrets.data }}
  {{ $key }}: {{ $value }}
  {{- end }}